version: "3.3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    environment:
     - CONFIG_PATH=./config/docker
    networks:
      - store_net
    depends_on:
      - db
  db:
    image: mysql:8.0
    command: --sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    networks:
      - store_net
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./dbscripts/:/docker-entrypoint-initdb.d:rw
    security_opt:
      - seccomp:unconfined

volumes:
  logvolume01: {}
  mysqldb8:

networks:
  store_net: